//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eikones
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfaecher
    {
        public tfaecher()
        {
            this.tpruefungens = new HashSet<tpruefungen>();
            this.tunterrichts = new HashSet<tunterricht>();
        }
    
        public string F_ID { get; set; }
        public string F_Name { get; set; }
    
        public virtual ICollection<tpruefungen> tpruefungens { get; set; }
        public virtual ICollection<tunterricht> tunterrichts { get; set; }
    }
}
