//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eikones
{
    using System;
    using System.Collections.Generic;
    
    public partial class tklassen
    {
        public tklassen()
        {
            this.tschuelers = new HashSet<tschueler>();
        }
    
        public string K_ID { get; set; }
    
        public virtual ICollection<tschueler> tschuelers { get; set; }
    }
}
