//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eikones
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpruefungen
    {
        public tpruefungen()
        {
            this.tpruefungen1 = new HashSet<tpruefungen>();
        }
    
        public int P_ID { get; set; }
        public int P_Schueler { get; set; }
        public string P_Lehrer { get; set; }
        public string P_Fach { get; set; }
        public Nullable<int> P_Note { get; set; }
        public Nullable<System.DateTime> P_Datum { get; set; }
        public Nullable<int> P_Vorgaenger { get; set; }
    
        public virtual tfaecher tfaecher { get; set; }
        public virtual tlehrer tlehrer { get; set; }
        public virtual ICollection<tpruefungen> tpruefungen1 { get; set; }
        public virtual tpruefungen tpruefungen2 { get; set; }
        public virtual tschueler tschueler { get; set; }
    }
}
