//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eikones
{
    using System;
    using System.Collections.Generic;
    
    public partial class traeume
    {
        public traeume()
        {
            this.tklassens = new HashSet<tklassen>();
            this.tunterrichts = new HashSet<tunterricht>();
        }
    
        public string R_ID { get; set; }
        public string R_Art { get; set; }
        public Nullable<int> R_Kapaz { get; set; }
    
        public virtual ICollection<tklassen> tklassens { get; set; }
        public virtual ICollection<tunterricht> tunterrichts { get; set; }
    }
}
