//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eikones
{
    using System;
    using System.Collections.Generic;
    
    public partial class tschueler
    {
        public tschueler()
        {
            this.tpruefungens = new HashSet<tpruefungen>();
        }
    
        public int S_ID { get; set; }
        public string S_Zuname { get; set; }
        public string S_Vorname { get; set; }
        public string S_Email { get; set; }
        public Nullable<System.DateTime> S_Gebdat { get; set; }
        public string S_Geschl { get; set; }
        public string S_Klasse { get; set; }
    
        public virtual tklassen tklassen { get; set; }
        public virtual ICollection<tpruefungen> tpruefungens { get; set; }
    }
}
