//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eikones
{
    using System;
    using System.Collections.Generic;
    
    public partial class tschueler
    {
        public string S_ID { get; set; }
        public string S_Vorname { get; set; }
        public string S_Nachname { get; set; }
        public string S_Klasse { get; set; }
    
        public virtual tklassen tklassen { get; set; }
    }
}
