//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eikones
{
    using System;
    using System.Collections.Generic;
    
    public partial class tunterricht
    {
        public int U_ID { get; set; }
        public string U_Klasse { get; set; }
        public string U_Lehrer { get; set; }
        public string U_Fach { get; set; }
        public string U_Raum { get; set; }
        public int U_Tag { get; set; }
        public int U_Stunde { get; set; }
    
        public virtual tfaecher tfaecher { get; set; }
        public virtual tklassen tklassen { get; set; }
        public virtual tlehrer tlehrer { get; set; }
        public virtual traeume traeume { get; set; }
        public virtual tstunden tstunden { get; set; }
    }
}
